name: generator
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: ^3.1.5

dependencies:
  flutter:
    sdk: flutter
  build:
  analyzer:
  source_gen:
  dart_style:
  change_case: 

dev_dependencies:
  build_runner: